---
title: "specCurvieR Examples"
author: "Zayne Sember"
output: html_notebook
---

```{r setup}
source("functions.R")
library(tidyverse)
```

```{r}
# Load CalCOFI public bottle dataset
#bottles <- read.csv("Data/bottle.csv")
#saveRDS(bottles, "Data/bottles.rds")
bottles <- readRDS("Data/bottles.rds")
```


```{r}
# sca_bottles <- sca(y="T_degC", x="Salnty", controls=c("STheta", "O2Sat", 
#                                                       "STheta*O2Sat", "ChlorA"),
#     data=bottles)
# 
# plotCurve(sca_bottles)
# plotVars(sca_bottles)

c_4 <- c("STheta", "O2Sat", "STheta*O2Sat", "ChlorA")
c_5 <- c("STheta", "O2Sat", "STheta*O2Sat", "ChlorA", "STheta*ChlorA")
c_10 <- c("STheta", "O2Sat", "STheta*O2Sat", "ChlorA", "STheta*ChlorA",
            "NH3uM", "NO2uM", "NH3uM*NO2uM", "SiO3uM", "NO2uM*SiO3uM")
c_15 <- c("STheta", "O2Sat", "STheta*O2Sat", "ChlorA", "STheta*ChlorA",
            "NH3uM", "NO2uM", "NH3uM*NO2uM", "SiO3uM", "NO2uM*SiO3uM",
            "STheta*SiO3uM", "O2Sat*SiO3uM", "STheta*SiO3uM", "ChlorA*SiO3uM",
            "NH3uM*SiO3uM")

plotSCV(y="T_degC", x="Salnty", controls=c_15,
    data=bottles, combine=T)
```

```{r}
source("functions.R")
temp2 <- sca(y="T_degC", x="Salnty", controls=c_5,
    data=bottles, parallel=F)

require(microbenchmark)

# Fixed effects with parallel not working
p <- microbenchmark(sca(y="T_degC", x="Salnty", controls=c_10, fixedEffects="R_Depth", data=bottles, parallel=T, workers=4), times=5)

np <- microbenchmark(sca(y="T_degC", x="Salnty", controls=c_10,
    data=bottles, fixedEffects="R_Depth", parallel=F), times=5)

autoplot(p)
autoplot(np)

sc1 <- ggplot(data=sca_bottles, aes(y=coef, x=index, fill=factor(sig.level))) +
  geom_ribbon(aes(ymin=coef-se, ymax=coef+se), alpha=.5) +
  geom_point(size=.75) +
  geom_hline(yintercept = 0, color="red", linetype="dashed", linewidth=.75) +
  labs(title="Ocean Temperature ~ Salinity", x="", y="Salinity coefficient") +
  theme_bw() +
  theme(
    axis.text.x = element_blank(),
    legend.position="top",
    legend.title=element_blank(),
    legend.key.size = unit(.4, 'cm')
  )

scp_bottles <- scp(sca_bottles)

sc2 <- ggplot(data=scp_bottles[[1]],
  aes(x=index,y=factor(controlID))
  ) +
  geom_point(shape="|", size=5) +
  labs(y="", x="") +
  scale_y_discrete(labels=scp_bottles[[2]], expand=c(.25,.25)) +
  theme_void() +
  theme(
    axis.text.y = element_text(size=6, hjust=0),
    axis.text.x = element_blank()
  )

grid::grid.newpage()
grid::grid.draw(rbind(ggplotGrob(sc1), ggplotGrob(sc2)))
```

